version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - "27017:27017"
    #environment:
    #   - MONGO_INITDB_ROOT_USERNAME=app_user
    #   - MONGO_INITDB_ROOT_PASSWORD=app_password
    #   - MONGO_INITDB_DATABASE=admin
    networks:
      - node-webapp-network

  server:
    container_name: webapp_server
    build: server/
    command: node server.js
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - node-webapp-network

  client:
    container_name: webapp_client
    build: client/
    command: npm run dev
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - node-webapp-network

networks:
  node-webapp-network:
    driver: bridge
